- name: PHP GEARMAN CLIENT | Install list of php gearman client nessesary packages
  apt: name={{item}}
  with_items:
    - gcc
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-all-dev
    - libevent-dev
    - cloog-ppl
    - gperf
    - uuid-dev
    - libgearman-dev
    - php-dev
    - supervisor

- unarchive:
   src: "{{ gearman_client_tarball_url }}"
   dest: "{{ default_download_directory }}"
   remote_src: true

- name: PHP GEARMAN CLIENT | Phpize
  command: "chdir={{ default_download_directory }}/{{ gearman_client_tarball_directory }} {{ item }}"
  with_items:
   - phpize
   - ./configure
   - make
   - make install

- name: PHP GEARMAN CLIENT | Write 20-gearman.ini
  copy: src=gearman.ini dest=/etc/php/5.6/mods-available/20-gearman.ini owner=root group=root mode=0644
  when: default_php_version == 5.6

- file:
    src: /etc/php/5.6/mods-available/20-gearman.ini
    dest: /etc/php/5.6/cli/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 5.6

- file:
    src: /etc/php/5.6/mods-available/20-gearman.ini
    dest: /etc/php/5.6/fpm/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 5.6

- name: PHP-FPM ROLE | Starting PHP-FPM
  service:
   name: php5.6-fpm
   state: restarted
  when: default_php_version == 5.6


- name: PHP GEARMAN CLIENT | Write 20-gearman.ini
  copy: src=gearman.ini dest=/etc/php/7.0/mods-available/20-gearman.ini owner=root group=root mode=0644
  when: default_php_version == 7.0

- file:
    src: /etc/php/7.0/mods-available/20-gearman.ini
    dest: /etc/php/7.0/cli/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.0

- file:
    src: /etc/php/7.0/mods-available/20-gearman.ini
    dest: /etc/php/7.0/fpm/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.0

- name: PHP-FPM ROLE | Restarting PHP-FPM
  service:
   name: php7.0-fpm
   state: restarted
  when: default_php_version == 7.0

- name: PHP GEARMAN CLIENT | Write 20-gearman.ini
  copy: src=gearman.ini dest=/etc/php/7.1/mods-available/20-gearman.ini owner=root group=root mode=0644
  when: default_php_version == 7.1

- file:
    src: /etc/php/7.1/mods-available/20-gearman.ini
    dest: /etc/php/7.1/cli/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.1

- file:
    src: /etc/php/7.1/mods-available/20-gearman.ini
    dest: /etc/php/7.1/fpm/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.1

- name: PHP-FPM ROLE | Restarting PHP-FPM
  service:
   name: php7.1-fpm
   state: restarted
  when: default_php_version == 7.1

- name: PHP GEARMAN CLIENT | Write 20-gearman.ini
  copy: src=gearman.ini dest=/etc/php/7.2/mods-available/20-gearman.ini owner=root group=root mode=0644
  when: default_php_version == 7.2

- file:
    src: /etc/php/7.2/mods-available/20-gearman.ini
    dest: /etc/php/7.2/cli/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.2

- file:
    src: /etc/php/7.2/mods-available/20-gearman.ini
    dest: /etc/php/7.2/fpm/conf.d/20-gearman.ini
    state: link
  become: true
  when: default_php_version == 7.2

- name: PHP-FPM ROLE | Restarting PHP-FPM
  service:
   name: php7.2-fpm
   state: restarted
  when: default_php_version == 7.2


